[tool.poetry]
name = "master-thesis"
version = "0.1.0"
description = ""
authors = ["Sarath S Menon <sarathmenon.downey@gmail.com>"]
readme = "README.md"
# package-mode = false

packages = [
    { include = "clicking/server", from = "bases" },
    { include = "clicking/segmentation", from = "components" },
    { include = "clicking/localization", from = "components" },
    { include = "clicking/visualization", from = "components" },
]

[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.4.0"
torchvision = "^0.19.0"
matplotlib = "^3.9.2"
transformers = "^4.44.0"
timm = "^1.0.8"
einops = "^0.8.0"
google-cloud-storage = "^2.18.2"
scipy = "^1.14.0"
pycocotools = "^2.0.8"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
ipykernel = "^6.29.5"

# [tool.poetry.scripts]
# init = "sh init_script.sh"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
