# yaml-language-server: $schema=./generated/config_schema.json

# Dataset settings
dataset:
  annotations_path: './datasets/annotation_dataset/coco_dataset_gcp/result.json'
  images_path: './datasets/gameplay_dataset/images'

# Prompt settings
prompts:
  refinement_path: './prompts/prompt_refinement.md'
  output_corrector_path: './prompts/output_corrector.md'
  word_limits:
    IMAGE_TO_OBJECT_DESCRIPTIONS:
      description_length: 30
      object_name: 5
    OBJECTS_LIST_TO_DESCRIPTIONS:
      description_length: 10
      object_name: 3

# Pipeline settings
pipeline:
  cache_dir: '.pipeline_cache'

# Visualization settings
visualization:
  figsize: [5, 5]

# Pipeline mode sequences
pipeline_mode_sequences:
  description_generation:
    prompt_mode: IMAGE_TO_OBJECT_DESCRIPTIONS