# yaml-language-server: $schema=./generated/config_schema.json

# Dataset settings
dataset:
  images_path: './datasets/label_studio_gen/coco_dataset/images'
  annotations_path: './datasets/label_studio_gen/coco_dataset/result.json'

# API settings
api:
  local_url: 'http://localhost:8082'
  cloud_url: 'http://localhost:8083'

# Model settings
models:
  localization:
    name: 'florence2'
    variant: 'florence-2-base'
    tasks:
      - 'LOCALIZATION_WITH_TEXT_OPEN_VOCAB'
  segmentation:
    name: 'sam2'
    variant: 'sam2_hiera_large'
    tasks: 
      - 'SEGMENTATION_WITH_BBOX'
  segmentation_with_text:
    name: 'evf_sam2'
    variant: 'sam2'
    tasks: 
      - 'SEGMENTATION_WITH_TEXT'
  ocr:
    name: 'florence2'
    variant: 'florence-2-base'
    tasks:
      - 'OCR'

# Prompt settings
prompts:
  refinement_path: './prompts/prompt_refinement.md'
  output_corrector_path: './prompts/output_corrector.md'
  word_limits:
    IMAGE_TO_OBJECT_DESCRIPTIONS:
      description_length: 30
      object_name: 5
    OBJECTS_LIST_TO_DESCRIPTIONS:
      description_length: 10
      object_name: 3

# Pipeline settings
pipeline:
  cache_dir: '.pipeline_cache'

# Visualization settings
visualization:
  figsize: [5, 5]

# Pipeline mode sequences
pipeline_mode_sequences:
  # object_detection_open_vocab:
  #   prompt_mode: IMAGE_TO_OBJECTS_LIST
  #   localization_input_mode: OBJ_DESCRIPTION
  #   localization_mode: LOCALIZATION_WITH_TEXT_OPEN_VOCAB
  #   bbox_verification_mode: CROP
  #   segmentation_mode: SEGMENTATION_WITH_BBOX
  object_detection_open_vocab:
    prompt_mode: IMAGE_TO_OBJECTS_LIST
    localization_input_mode: OBJ_NAME
    localization_mode: LOCALIZATION_WITH_TEXT_OPEN_VOCAB
    bbox_verification_mode: CROP
    segmentation_mode: SEGMENTATION_WITH_BBOX
  # object_detection_text_grounded:
  #   prompt_mode: IMAGE_TO_OBJECTS_LIST
  #   localization_input_mode: OBJ_NAME
  #   localization_mode: LOCALIZATION_WITH_TEXT_GROUNDED
  #   bbox_verification_mode: CROP
  #   segmentation_mode: SEGMENTATION_WITH_BBOX
 