# %%
import torch
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import requests

DATA_DIR = "./datasets/resized_media/gameplay_images/"
# %%
# image_orig = Image.open(f"{DATA_DIR}/hogwarts_legacy/2.jpg")

url = "https://github.com/SauravMaheshkar/SauravMaheshkar/blob/main/assets/text2img/llama_spiderman_coffee.png?raw=true"
image = Image.open(requests.get(url, stream=True).raw)
image = np.array(image.convert("RGB"))
plt.imshow(image)
plt.grid(False)
plt.axis(False)
plt.show()
#%%

from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator
from sam2.utils.misc import variant_to_config_mapping
from sam2.utils.visualization import show_masks
from sam2 import load_model

model = load_model(
    variant="tiny",
    ckpt_path="./models/sam2_hiera_tiny.pt",
    device="cpu"
)

mask_generator = SAM2AutomaticMaskGenerator(model)
masks = mask_generator.generate(image)
     
output_mask = show_masks( 
    image=image, masks=masks, scores=None, only_best=False, autogenerated_mask=True
)
output_mask
# %%